# Generated by Django 5.1.4 on 2025-06-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Instructor', models.CharField(max_length=100)),
                ('Start_time', models.DateTimeField()),
                ('Total_slot', models.PositiveIntegerField()),
                ('Availabel_slot', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_name', models.CharField(max_length=100)),
                ('Client_email', models.EmailField(max_length=254)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('Fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fitnessclass')),
            ],
        ),
    ]
