# Generated by Django 5.2.2 on 2025-06-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessclass',
            old_name='Availabel_slot',
            new_name='Available_slot',
        ),
    ]
