# Generated by Django 5.2.2 on 2025-06-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_availabel_slot_fitnessclass_available_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessclass',
            old_name='Available_slot',
            new_name='Availabel_slot',
        ),
    ]
